baseURL = "https://blog.indonesiadot.com/"
languageCode = "en-us"
title = "Blog Indonesiadot.Com"
theme = "lanyonindo"

Paginate = 9
Pagination = 3
canonifyurls = true
[permalinks]
  post = "/:year/:month/:day/:title/"
  #post = "/:slug/"
  fixed = "/:title/"

[params]
  Title = "Blog Indonesiadot.Com"
  Tagline = "Web log of Indonesiadot.Com, Linux and updated technology"
  Author = "Widya"
